//Page Titles
export const PAGE_TITLE_CREATE = "Create :type"
export const PAGE_TITLE_UPDATE = "Update :type ':name'"
export const PAGE_TITLE_VIEW = "View :type ':name'"
export const PAGE_TITLE_LIST = ":type List"

//User
export const USER = "User"
export const ID = "ID"
export const USERNAME = "Username"
export const ROLE = "Role"
export const FIRST_NAME = "First Name"
export const LAST_NAME = "Last Name"
export const EMAIL = "Email"
export const ADDRS = "Address"
export const PHONE1 = "Phone Number 1"
export const PHONE2 = "Phone Number 2"
export const PASSWORD = "Password"
export const CONFIRM_PASSWORD = "Confirm Password"
export const ENABLED = "Enabled"
export const LOCKED = "Locked"
export const CREATED_AT = "Created At"
export const CREATED_BY = "Created By"
export const UPDATED_AT = "Updated At"
export const UPDATED_BY = "Updated By"
export const DELETED_AT = "Deleted At"
export const DELETED_BY = "Deleted By"

//Table Headers
export const TABLE_NAME = "Name"
export const TABLE_ROLE = "Role"
export const TABLE_LOCK_STATUS = "Locked"
export const TABLE_STATUS = "Active"
export const TABLE_ACTION = "Actions"